#!/usr/bin/env bash
#
# End-to-end check of the deployed redaction chaincode.
#
#   ./smoke.sh          run every check against the live network
#
# Requires a network brought up by network.sh with the chaincode deployed.
#
# WHY IT EXISTS. The contract's unit tests prove its logic in Go. They cannot
# prove that the deployed contract enforces the same rules: packaging, the
# external builder, the channel definition and the peer's endorsement path all
# sit between the source and what actually runs. Every check below has already
# caught something real once — the Schnorr sign error, the ccaas package layout,
# a swallowed install failure — and each failed in a way that pointed somewhere
# other than its cause.
#
# The positive check uses a signature produced by pkg/crypto, so a divergence
# between the two Schnorr implementations fails here as well as in
# TestChaincodeVerifiesPkgCryptoSignatures.

set -euo pipefail

NET_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHANNEL="${CHANNEL:-redaction}"
CC_NAME="${CC_NAME:-redaction}"
# Same resolution order as network.sh: an explicit FABRIC_BIN wins, then the
# location scripts/setup-ec2.sh installs to, then whatever is already on PATH.
if [[ -n "${FABRIC_BIN:-}" ]]; then
  :
elif [[ -x "$HOME/fabric/bin/peer" ]]; then
  FABRIC_BIN="$HOME/fabric/bin"
elif command -v peer >/dev/null 2>&1; then
  FABRIC_BIN="$(dirname "$(command -v peer)")"
else
  FABRIC_BIN="$HOME/fabric/bin"
fi

RED=$'\e[31m'; GRN=$'\e[32m'; BLD=$'\e[1m'; RST=$'\e[0m'
pass=0; fail=0

ok()   { printf '%s  PASS%s  %s\n' "$GRN" "$RST" "$1"; pass=$((pass+1)); }
bad()  { printf '%s  FAIL%s  %s\n'  "$RED" "$RST" "$1"; fail=$((fail+1)); }
step() { printf '\n%s==> %s%s\n' "$BLD" "$1" "$RST"; }

export PATH="$FABRIC_BIN:$PATH"
command -v peer >/dev/null 2>&1 || { echo "peer not found; set FABRIC_BIN" >&2; exit 2; }
[[ -f "$NET_DIR/.topology" ]] || { echo "no network is up; run network.sh up first" >&2; exit 2; }

ORG="$NET_DIR/organizations/peerOrganizations/org1.example.com"
ORD="$NET_DIR/organizations/ordererOrganizations/example.com/orderers/orderer0.example.com/tls/ca.crt"

export FABRIC_CFG_PATH="$FABRIC_BIN/../config"
export CORE_PEER_TLS_ENABLED=true
export CORE_PEER_LOCALMSPID=Org1MSP
export CORE_PEER_TLS_ROOTCERT_FILE="$ORG/peers/peer0.org1.example.com/tls/ca.crt"
export CORE_PEER_MSPCONFIGPATH="$ORG/users/Admin@org1.example.com/msp"

# peer0.org1 sits on a different port per topology; compose exposes it at 7051
# for minimal and 11051 for full.
if [[ "$(cat "$NET_DIR/.topology")" == "full" ]]; then
  export CORE_PEER_ADDRESS=localhost:11051
else
  export CORE_PEER_ADDRESS=localhost:7051
fi

# Golden vectors, generated by pkg/crypto and shared with
# network/chaincode/redaction/contract_test.go. If those constants change there,
# change them here too — they are the same key and the same signatures.
PUB_X="84e1a05364cf2f8dcc42a03ad4d33b8bc4085691298e32af70b5aeed99008b9d"
PUB_Y="6bf002766e0b3f68ed5ecaa8ed310efd013fdd0190a49597a58aa56b4a8a682c"
YES_E="560ee83d3df849623a36baac5c0b4ac04ce093d51f7af97573a3eb70170217d"
YES_S="385d825ccf1e3774efd311f6270d46d8ebc09fe6439b6e969a8a66c5a078487b"
REQ_ID="req-golden-0001"

# invoke <json> -> prints combined output
# PEER_ARGS names one peer per organisation.
#
# The full channel's endorsement policy is MAJORITY across organisations, so an
# invoke aimed at a single peer fails with ENDORSEMENT_POLICY_FAILURE, which
# reports the transaction as invalid without saying too few orgs endorsed it.
# Collecting from every org is also what exercises the cross-organisation path
# the full topology exists to provide.
PEER_ARGS=()
if [[ "$(cat "$NET_DIR/.topology")" == "full" ]]; then
  for o in 1 2 3 4; do
    PEER_ARGS+=(--peerAddresses "localhost:$((11051 + 1000 * (2 * (o - 1))))")
    PEER_ARGS+=(--tlsRootCertFiles "$NET_DIR/organizations/peerOrganizations/org$o.example.com/peers/peer0.org$o.example.com/tls/ca.crt")
  done
else
  PEER_ARGS+=(--peerAddresses localhost:7051)
  PEER_ARGS+=(--tlsRootCertFiles "$ORG/peers/peer0.org1.example.com/tls/ca.crt")
fi

invoke() {
  peer chaincode invoke     -o localhost:7050 --ordererTLSHostnameOverride orderer0.example.com     --tls --cafile "$ORD" -C "$CHANNEL" -n "$CC_NAME"     "${PEER_ARGS[@]}"     -c "$1" --waitForEvent 2>&1 || true
}

# expect_ok <description> <json>
expect_ok() {
  local desc="$1" payload="$2" out
  out=$(invoke "$payload")
  if grep -q "status:200" <<<"$out"; then
    ok "$desc"
  else
    bad "$desc"
    printf '        %s\n' "$(grep -oE 'message:"[^"]*"|Error.*' <<<"$out" | head -1)"
  fi
}

# expect_reject <description> <expected substring> <json>
#
# Matching the message matters: a rejection for the wrong reason is not the
# guard being tested. An invalid signature rejected as "already voted" would
# leave the signature check unexercised.
expect_reject() {
  local desc="$1" want="$2" payload="$3" out
  out=$(invoke "$payload")
  if grep -q "status:200" <<<"$out"; then
    bad "$desc — the contract ACCEPTED it"
  elif grep -q "$want" <<<"$out"; then
    ok "$desc"
  else
    bad "$desc — rejected, but not for the expected reason"
    printf '        want: %s\n' "$want"
    printf '        got:  %s\n' "$(grep -oE 'message:"[^"]*"' <<<"$out" | head -1)"
  fi
}

round_json() {
  local addr="$1"
  printf '{\\"contract_addr\\":\\"%s\\",\\"request_id\\":\\"%s\\",\\"target_tx_id\\":\\"tx-1\\",\\"requester_id\\":\\"id-golden\\",\\"cert\\":{\\"requester_known\\":true,\\"redactable\\":true,\\"satisfies\\":true,\\"attributes\\":\\"S OR R OR V\\"},\\"committee_size\\":1,\\"threshold\\":1}' "$addr" "$REQ_ID"
}

ballot_json() {
  local node="$1" approve="$2" e="$3" s="$4"
  printf '{\\"node_id\\":\\"%s\\",\\"approve\\":%s,\\"e\\":\\"%s\\",\\"s\\":\\"%s\\"}' "$node" "$approve" "$e" "$s"
}

SUFFIX="$(date +%s)"

step "Setup"
expect_ok "register the node set" \
  "{\"function\":\"RegisterNodes\",\"Args\":[\"[{\\\"id\\\":\\\"id-golden\\\",\\\"attributes\\\":{\\\"validator\\\":\\\"true\\\"},\\\"pub_x\\\":\\\"$PUB_X\\\",\\\"pub_y\\\":\\\"$PUB_Y\\\"}]\"]}"

step "Happy path"
ADDR="con-golden-0001"
expect_ok "open a voting round" \
  "{\"function\":\"Init\",\"Args\":[\"$(round_json "$ADDR")\"]}"

expect_ok "a pkg/crypto signature is accepted on chain" \
  "{\"function\":\"Vote\",\"Args\":[\"$ADDR\",\"$(ballot_json id-golden true "$YES_E" "$YES_S")\"]}"

step "Guards"
# Each guard gets a fresh round, so it is exercised as the FIRST vote. Reusing
# a round would let the one-vote-per-member rule fire first and leave the
# signature and membership checks untested.
FORGE="con-forge-$SUFFIX"
expect_ok "open a round for the forgery check" \
  "{\"function\":\"Init\",\"Args\":[\"$(round_json "$FORGE")\"]}"
expect_reject "a forged signature is rejected" "invalid vote signature" \
  "{\"function\":\"Vote\",\"Args\":[\"$FORGE\",\"$(ballot_json id-golden true "660ee83d3df849623a36baac5c0b4ac04ce093d51f7af97573a3eb70170217d" "$YES_S")\"]}"

REPLAY="con-replay-$SUFFIX"
expect_ok "open a round for the replay check" \
  "{\"function\":\"Init\",\"Args\":[\"$(round_json "$REPLAY")\"]}"
expect_reject "a signature from another round is rejected" "invalid vote signature" \
  "{\"function\":\"Vote\",\"Args\":[\"$REPLAY\",\"$(ballot_json id-golden true "$YES_E" "$YES_S")\"]}"

OUTSIDER="con-outsider-$SUFFIX"
expect_ok "open a round for the membership check" \
  "{\"function\":\"Init\",\"Args\":[\"$(round_json "$OUTSIDER")\"]}"
expect_reject "a non-committee node is rejected" "is not on the committee" \
  "{\"function\":\"Vote\",\"Args\":[\"$OUTSIDER\",\"$(ballot_json id-outsider true "$YES_E" "$YES_S")\"]}"

expect_reject "a second vote from the same member is rejected" "already voted" \
  "{\"function\":\"Vote\",\"Args\":[\"$ADDR\",\"$(ballot_json id-golden true "$YES_E" "$YES_S")\"]}"

step "Summary"
printf '     %d passed, %d failed\n' "$pass" "$fail"
if (( fail > 0 )); then
  printf '\n%sThe deployed contract does not enforce its rules. Do not record results.%s\n' "$RED" "$RST"
  exit 1
fi
if [[ "$(cat "$NET_DIR/.topology")" == "minimal" ]]; then
  printf '\n     Note: minimal topology — this verifies the mechanism, not the cost.\n'
fi
printf '\n%sThe deployed contract enforces every checked rule.%s\n' "$GRN" "$RST"
