#!/usr/bin/env bash
#
# End-to-end check of the deployed redaction chaincode.
#
#   ./smoke.sh          run every check against the live network
#
# Requires a network brought up by network.sh with the chaincode deployed.
#
# WHY IT EXISTS. The contract's unit tests prove its logic in Go. They cannot
# prove that the deployed contract enforces the same rules: packaging, the
# external builder, the channel definition and the peer's endorsement path all
# sit between the source and what actually runs. Every check below has already
# caught something real once — the Schnorr sign error, the ccaas package layout,
# a swallowed install failure — and each failed in a way that pointed somewhere
# other than its cause.
#
# The positive check uses a signature produced by pkg/crypto, so a divergence
# between the two Schnorr implementations fails here as well as in
# TestChaincodeVerifiesPkgCryptoSignatures.

set -euo pipefail

NET_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHANNEL="${CHANNEL:-redaction}"
CC_NAME="${CC_NAME:-redaction}"
# Same resolution order as network.sh: an explicit FABRIC_BIN wins, then the
# location scripts/setup-ec2.sh installs to, then whatever is already on PATH.
if [[ -n "${FABRIC_BIN:-}" ]]; then
  :
elif [[ -x "$HOME/fabric/bin/peer" ]]; then
  FABRIC_BIN="$HOME/fabric/bin"
elif command -v peer >/dev/null 2>&1; then
  FABRIC_BIN="$(dirname "$(command -v peer)")"
else
  FABRIC_BIN="$HOME/fabric/bin"
fi

RED=$'\e[31m'; GRN=$'\e[32m'; BLD=$'\e[1m'; RST=$'\e[0m'
pass=0; fail=0

ok()   { printf '%s  PASS%s  %s\n' "$GRN" "$RST" "$1"; pass=$((pass+1)); }
bad()  { printf '%s  FAIL%s  %s\n'  "$RED" "$RST" "$1"; fail=$((fail+1)); }
step() { printf '\n%s==> %s%s\n' "$BLD" "$1" "$RST"; }

export PATH="$FABRIC_BIN:$PATH"
command -v peer >/dev/null 2>&1 || { echo "peer not found; set FABRIC_BIN" >&2; exit 2; }
[[ -f "$NET_DIR/.topology" ]] || { echo "no network is up; run network.sh up first" >&2; exit 2; }

ORG="$NET_DIR/organizations/peerOrganizations/org1.example.com"
ORD="$NET_DIR/organizations/ordererOrganizations/example.com/orderers/orderer0.example.com/tls/ca.crt"

export FABRIC_CFG_PATH="$FABRIC_BIN/../config"
export CORE_PEER_TLS_ENABLED=true
export CORE_PEER_LOCALMSPID=Org1MSP
export CORE_PEER_TLS_ROOTCERT_FILE="$ORG/peers/peer0.org1.example.com/tls/ca.crt"
export CORE_PEER_MSPCONFIGPATH="$ORG/users/Admin@org1.example.com/msp"

# peer0.org1 sits on a different port per topology; compose exposes it at 7051
# for minimal and 11051 for full.
if [[ "$(cat "$NET_DIR/.topology")" == "full" ]]; then
  export CORE_PEER_ADDRESS=localhost:11051
else
  export CORE_PEER_ADDRESS=localhost:7051
fi

# Golden vectors, generated by pkg/crypto and shared with
# network/chaincode/redaction/contract_test.go. If those constants change there,
# change them here too — they are the same key and the same signatures.
PUB_X="b07b38cbba315fa1ed0597049ba3514be6e86e190400bef368f6c02c84c8c716"
PUB_Y="701ce97bf410478f263d55922292fc9f70d48c6281262817cc3aa103495c8cef"
YES_E="33b3e03afbe5ec307810e3409e681a3ea15424a48db20950063fece372d28a0c"
YES_S="056d993f8897f8127cfaa391e5b38cf5e1bb7009e1219e585930db7e2187cc97"

# The CA key that signs P_C, and its signature over the golden certificate.
# Same vectors as network/chaincode/redaction/contract_test.go.
CA_PUB_X="5d78e3a8b6e42894b9abb7f178c6970ae6d6115f1ade994b6259ade8c9b7a3af"
CA_PUB_Y="4b387ebb70ab16aa93bab9671ea56b1499700138d9bce809afcba723cb7200b9"
CERT_SIG_E="432e25f82cc6cd1a29aba737f96596bd60504bed53799383ce3f440f4dd50fab"
CERT_SIG_S="8bcd77f70facf94c6b108f954410ca9b9bb546ecca5090c34bf3650547b073ef"
REQ_ID="req-golden-0001"

# invoke <json> -> prints combined output
# PEER_ARGS names one peer per organisation.
#
# The full channel's endorsement policy is MAJORITY across organisations, so an
# invoke aimed at a single peer fails with ENDORSEMENT_POLICY_FAILURE, which
# reports the transaction as invalid without saying too few orgs endorsed it.
# Collecting from every org is also what exercises the cross-organisation path
# the full topology exists to provide.
PEER_ARGS=()
if [[ "$(cat "$NET_DIR/.topology")" == "full" ]]; then
  for o in 1 2 3 4; do
    PEER_ARGS+=(--peerAddresses "localhost:$((11051 + 1000 * (2 * (o - 1))))")
    PEER_ARGS+=(--tlsRootCertFiles "$NET_DIR/organizations/peerOrganizations/org$o.example.com/peers/peer0.org$o.example.com/tls/ca.crt")
  done
else
  PEER_ARGS+=(--peerAddresses localhost:7051)
  PEER_ARGS+=(--tlsRootCertFiles "$ORG/peers/peer0.org1.example.com/tls/ca.crt")
fi

invoke() {
  peer chaincode invoke     -o localhost:7050 --ordererTLSHostnameOverride orderer0.example.com     --tls --cafile "$ORD" -C "$CHANNEL" -n "$CC_NAME"     "${PEER_ARGS[@]}"     -c "$1" --waitForEvent 2>&1 || true
}

# expect_ok <description> <json>
expect_ok() {
  local desc="$1" payload="$2" out
  out=$(invoke "$payload")
  if grep -q "status:200" <<<"$out"; then
    ok "$desc"
  else
    bad "$desc"
    printf '        %s\n' "$(grep -oE 'message:"[^"]*"|Error.*' <<<"$out" | head -1)"
  fi
}

# expect_reject <description> <expected substring> <json>
#
# Matching the message matters: a rejection for the wrong reason is not the
# guard being tested. An invalid signature rejected as "already voted" would
# leave the signature check unexercised.
expect_reject() {
  local desc="$1" want="$2" payload="$3" out
  out=$(invoke "$payload")
  if grep -q "status:200" <<<"$out"; then
    bad "$desc — the contract ACCEPTED it"
  elif grep -q "$want" <<<"$out"; then
    ok "$desc"
  else
    bad "$desc — rejected, but not for the expected reason"
    printf '        want: %s\n' "$want"
    printf '        got:  %s\n' "$(grep -oE 'message:"[^"]*"' <<<"$out" | head -1)"
  fi
}

policy_json() {
  printf '{\\"committee_size\\":1,\\"threshold\\":1,\\"ca_pub_x\\":\\"%s\\",\\"ca_pub_y\\":\\"%s\\"}' "$CA_PUB_X" "$CA_PUB_Y"
}

# cert_json <sig_e> <sig_s>
#
# The CA-signed P_C. It rides on the ballot now that there is no Init to store
# it, so the signature is what stops a caller asserting its own eligibility.
cert_json() {
  local sig_e="$1" sig_s="$2"
  printf '\\"cert\\":{\\"target_tx_id\\":\\"tx-golden-0001\\",\\"requester_id\\":\\"id-golden\\",\\"requester_known\\":true,\\"redactable\\":true,\\"satisfies\\":true,\\"policy_id\\":\\"pol-golden\\",\\"policy_ver\\":1,\\"attributes\\":\\"S OR R OR V\\",\\"sig_e\\":\\"%s\\",\\"sig_s\\":\\"%s\\"}' "$sig_e" "$sig_s"
}

# ballot_json <node> <approve> <e> <s> [cert_sig_e] [cert_sig_s]
ballot_json() {
  local node="$1" approve="$2" e="$3" s="$4"
  # ${5-...}, NOT ${5:-...}. The colon form substitutes the default for an
  # empty string as well as an unset one, so passing "" to mean "no CA
  # signature" silently produced a correctly signed certificate — and the
  # unsigned-certificate check then failed on the ballot signature instead,
  # leaving the CA guard untested while looking like it had run.
  local cse="${5-$CERT_SIG_E}" css="${6-$CERT_SIG_S}"
  printf '{\\"node_id\\":\\"%s\\",\\"approve\\":%s,\\"request_id\\":\\"%s\\",\\"target_tx_id\\":\\"tx-golden-0001\\",%s,\\"e\\":\\"%s\\",\\"s\\":\\"%s\\"}' \
    "$node" "$approve" "$REQ_ID" "$(cert_json "$cse" "$css")" "$e" "$s"
}

SUFFIX="$(date +%s)"

step "Setup"
expect_ok "register the node set" \
  "{\"function\":\"RegisterNodes\",\"Args\":[\"[{\\\"id\\\":\\\"id-golden\\\",\\\"attributes\\\":{\\\"validator\\\":\\\"true\\\"},\\\"pub_x\\\":\\\"$PUB_X\\\",\\\"pub_y\\\":\\\"$PUB_Y\\\"}]\"]}"

expect_ok "register the round policy" \
  "{\"function\":\"RegisterRoundPolicy\",\"Args\":[\"$(policy_json)\"]}"

step "Happy path"
# NO ROUND TO OPEN. Init cost a block before any ballot could read what it
# wrote; the committee is recomputed per ballot instead (Eq. 7 is a pure
# function) and {req, sigma} rides on the ballot under the CA's signature.
ADDR="con-golden-0001"

expect_ok "a pkg/crypto signature is accepted on chain" \
  "{\"function\":\"Vote\",\"Args\":[\"$ADDR\",\"$(ballot_json id-golden true "$YES_E" "$YES_S")\"]}"

step "Guards"
# Each guard gets a fresh round, so it is exercised as the FIRST vote. Reusing
# a round would let the one-vote-per-member rule fire first and leave the
# signature and membership checks untested.
FORGE="con-forge-$SUFFIX"
expect_reject "a forged signature is rejected" "invalid vote signature" \
  "{\"function\":\"Vote\",\"Args\":[\"$FORGE\",\"$(ballot_json id-golden true "660ee83d3df849623a36baac5c0b4ac04ce093d51f7af97573a3eb70170217d" "$YES_S")\"]}"

REPLAY="con-replay-$SUFFIX"
expect_reject "a signature from another round is rejected" "invalid vote signature" \
  "{\"function\":\"Vote\",\"Args\":[\"$REPLAY\",\"$(ballot_json id-golden true "$YES_E" "$YES_S")\"]}"

OUTSIDER="con-outsider-$SUFFIX"
expect_reject "a non-committee node is rejected" "is not on the committee" \
  "{\"function\":\"Vote\",\"Args\":[\"$OUTSIDER\",\"$(ballot_json id-outsider true "$YES_E" "$YES_S")\"]}"

UNSIGNED="con-unsigned-$SUFFIX"
expect_reject "a certificate the CA did not sign is rejected" "valid CA signature" \
  "{\"function\":\"Vote\",\"Args\":[\"$UNSIGNED\",\"$(ballot_json id-golden true "$YES_E" "$YES_S" "" "")\"]}"

TAMPERED="con-tampered-$SUFFIX"
expect_reject "a certificate altered after signing is rejected" "valid CA signature" \
  "{\"function\":\"Vote\",\"Args\":[\"$TAMPERED\",\"$(ballot_json id-golden true "$YES_E" "$YES_S" "aa45099cb28c1dd1b79ac8e3b459ff9d9823e329c1b82a156cdbf1f3413785de" "$CERT_SIG_S")\"]}"

expect_reject "a second vote from the same member is rejected" "already voted" \
  "{\"function\":\"Vote\",\"Args\":[\"$ADDR\",\"$(ballot_json id-golden true "$YES_E" "$YES_S")\"]}"

step "Summary"
printf '     %d passed, %d failed\n' "$pass" "$fail"
if (( fail > 0 )); then
  printf '\n%sThe deployed contract does not enforce its rules. Do not record results.%s\n' "$RED" "$RST"
  exit 1
fi
if [[ "$(cat "$NET_DIR/.topology")" == "minimal" ]]; then
  printf '\n     Note: minimal topology — this verifies the mechanism, not the cost.\n'
fi
printf '\n%sThe deployed contract enforces every checked rule.%s\n' "$GRN" "$RST"
